### ISSUE TITLE
Error in console after opening/hacking first door paleto bank

### ISSUE THREAD

**Issue by Glen92** [qbcore-framework/qb-scoreboard#20]
![image](https://user-images.githubusercontent.com/42032794/152659662-fd1292a8-a7a6-472e-97eb-f6477b485519.png)

**Comment by Roberto0202** [comment]
--add paleto state --confing.lua 
--step 1
Config.IllegalActions = {
    ["storerobbery"] = {
        minimum = 2,
        busy = false,
    },
    ["bankrobbery"] = {
        minimum = 3,
        busy = false,
    },
    ["paleto"] = {
        minimum = 3,
        busy = false,
    },
    ["jewellery"] = {
        minimum = 3,
        busy = false,
    },
    ["pacific"] = {
        minimum = 5,
        busy = false,
    },
}
--step 2 edit qb-scoreboard/html/ui 
--add this anywere after lane 22
<div class="scoreboard-info-beam" data-type="paleto">
                        <div class="info-beam-title">
                            <p>Rop Banke Paleto</p>
                        </div>
                        <div class="info-beam-status"></div>
                    </div>

YW . enjoy
