### ISSUE TITLE
onesync infinity not compatible 

### ISSUE THREAD

**Issue by RadhwaneDZ** [qbcore-framework/qb-scoreboard#5]
scoreboard is not compatible with onesync infinity 
is there anyway how to make it work with onesync infinity ?

**Comment by GhzGarage** [comment]
@BerkieBb isn't it?

**Comment by BerkieBb** [comment]
This should already be compatible with onesync infinity, if you look at the code it gets the players from the server side

**Comment by ihyajb** [comment]
Also just tested and yes its already compatible with onesync
